name 'ppouliot-openstack_hyper_v'
version '0.0.1'
source 'https://github.com/ppouliot/ppouliot-openstack_hyper_v.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache 2.0'
summary 'Module for building hyper-v/openstack compute'
description 'puppet module for creating a hyper-v compute nodes'
dependency 'puppetlabs-powershell'
dependency 'cprice404/inifile', '>= 0.9.0'
