name 'puppet-openstack_hyper_v'
version '0.0.1'
source 'https://github.com/openstack-hyper-v/puppet-openstack_hyper_v.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache 2.0'
summary 'Module for building hyper-v/openstack compute'
description 'puppet module for creating a hyper-v compute nodes'
dependency 'puppetlabs/stdlib'
dependency 'openstack-hyper-v/nova_hyper_v'
dependency 'openstack-hyper-v/ceilometer_hyper_v'
