name 'ppouliot-openstack-hyper-v'
version '0.0.1'
source 'https://github.com/ppouliot/ppouliot-openstack-hyper-v.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache 2.0'
summary 'Module for building hyper-v/openstack compute'
description 'puppet module for creating a hyper-v compute nodes'
dependency 'joshcooper-powershell'
